### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-js-package-json-intro-AjvZZg#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://goshuama-kg-tgc7noax99ajvzzg.surge.sh/) and meets the following criteria:

- [x] Start your project with [these old game files](https://gist.github.com/egillespie/61d72035cd8c2639f07db1dbe2010605)
- [x] Convert the game's CSS to Sass, using variables, functions, and nesting where appropriate
- [x] Write a `dev` script in `package.json` that auto-compiles Sass and refreshes the browser at the same time
- [x] Write a `build` script in `package.json` that lints HTML, Sass, and JavaScript files before compiling Sass files (you can use these linters: [htmlhint](https://www.npmjs.com/package/htmlhint) for HTML, [stylelint](https://www.npmjs.com/package/stylelint) and [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard#installation) for Sass, [standard](https://www.npmjs.com/package/standard) for JavaScript)
- [x] All linting problems are fixed (problems will be displayed in the terminal when you run `yarn build`)
- [x] Write a `deploy` script in `package.json` that builds the project and uploads it to Surge if there are no errors
- [x] Unnecessary files like `node_modules` and your compiled CSS do not exist in your repository
- [x] Unnecessary files like `package.json` and `yarn.lock` are not uploaded to Surge

**Comment by stuartpearman** [comment]
Hi Amanuel, your scripts should also lint your program:

> Write a build script in package.json that lints HTML, Sass, and JavaScript files before compiling Sass files (you can use these linters: htmlhint for HTML, stylelint and stylelint-config-standard for Sass, standard for JavaScript)

You can add each package with Yarn and lint HTML, JS, and CSS before deployment.

Let me know if you have questions.

**Comment by amanuel1995** [comment]
I thought I did that and added the linters as dependencies on my JSON file. Are you saying I should have made that a build script instead of adding them as dependencies? If so I have moved the linters into dev dependencies. Take a look and get back to me.

**Comment by amanuel1995** [comment]
I have pushed in my work. I have updated the package.json file to include scripts to run the linters for sass, html and JS. Take a look at it. I'm pretty sure I fixed it. 😄

**Comment by stuartpearman** [comment]
Nice! It works. The only thing I noticed is that in your `js-lint` script you have:

```
"js-lint": "yarn standard script.js"
```

You could instead just put:

```
"js-lint": "standard script.js"
```

The second would be slightly more correct, but it doesn't seem to affect the command, it still works fine. Nice work, I know this one was a little tricky 💯 :shipit:

**Comment by amanuel1995** [comment]
First I did that and it did not work for me and Katie told me to put yarn in there. That's why I did it.
